#ifndef BIGOS_INCLUDE_STDBIGOS_ERROR
#define BIGOS_INCLUDE_STDBIGOS_ERROR

typedef enum [[nodiscard]] {
	ERR_NONE = 0,
	ERR_NOT_IMPLEMENTED,
	ERR_NOT_VALID,
	ERR_BAD_ARG,
	ERR_PHYSICAL_MEMORY_FULL,
	ERR_OUT_OF_BOUNDS,
	ERR_NOT_INITIALIZED,
	ERR_NOT_FOUND,
} error_t;

#endif // !BIGOS_INCLUDE_STDBIGOS_ERROR

